services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: inquire_user
      POSTGRES_PASSWORD: inquire_pass
      POSTGRES_DB: inquire_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inquire_user -d inquire_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
